services:
  dev_db:
    container_name: dev_db
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
        - freecodecamp
networks:
  freecodecamp: